### ISSUE TITLE
Add arm64 as platform

### ISSUE THREAD

**Issue by BabyDino** [brablc/swarm-certbot-traefik#1]
Hi! Really intrigued by your solution for managing certs when running multiple traefik instances.

Any chance you can add the arm64 platform to the push action?

**Comment by brablc** [comment]
Added in commit f2c8fecca9c11286fcdbf60f795314afeee5cbd0 . I can see that build succeeded, but I would welcome if you can try and verify.

**Comment by BabyDino** [comment]
Container starts on arm64. Will create new issue if I encounter any. Thanks!
